# Generated by Django 3.1.13 on 2021-12-31 21:00

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='+23566200135', max_length=30, region=None, verbose_name='Phone Number')),
                ('about_me', models.TextField(default='Say Something about yourself', verbose_name='About me')),
                ('licence', models.CharField(blank=True, max_length=40, null=True, verbose_name='Django Rest API Licence')),
                ('profile_photo', models.ImageField(default='/profile_default.png', upload_to='', verbose_name='profile photo')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='profile photo')),
                ('country', django_countries.fields.CountryField(default='TCD', max_length=2, verbose_name='Country')),
                ('city', models.CharField(default='Ndjamena', max_length=80, verbose_name='City')),
                ('is_buyer', models.BooleanField(default=False, help_text='Are you looking to Buy Property ? ', verbose_name='Buyer')),
                ('is_seller', models.BooleanField(default=False, help_text='Are you looking to Sell Property ? ', verbose_name='Seller')),
                ('is_agent', models.BooleanField(default=False, help_text='Are you Agent ? ', verbose_name='Agent')),
                ('Top_agent', models.BooleanField(default=False, verbose_name='To Agent')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('num_reviews', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of Reviews')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
